In [1]:
import numpy as np

In [2]:
one_d_array = np.array([1, 2, 3, 4, 5])
print("One-D array: ", one_d_array)
one_d_array[2]

One-D array:  [1 2 3 4 5]


3

In [3]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(two_d_array)
two_d_array[2][2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9

In [4]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [5]:
reshaped = arr.reshape(2, 3)
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
zeros = np.zeros((4, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
ones = np.ones((2, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
empty = np.empty((3, 2))
empty

array([[1.09766500e-316, 0.00000000e+000],
       [3.62861280e-312, 2.78310358e-309],
       [5.30614223e-313, 8.44852254e-322]])

In [9]:
eye = np.eye(2)
eye

array([[1., 0.],
       [0., 1.]])

In [10]:
linespace = np.linspace(0, 1, 4)
print(linespace)
linespace[1]

[0.         0.33333333 0.66666667 1.        ]


0.3333333333333333

In [11]:
import pandas as pd

In [12]:
# Creating a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
print(df)
df["Age"][0]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


25

In [13]:
json_data = '{"Name": ["Alice", "Bob", "Charlie"], "Age": [25, 30, 35]}'

df_json = pd.read_json((json_data))
print(df_json)
df_json["Name"]


      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


/tmp/ipykernel_7695/4064676641.py:3: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_json = pd.read_json((json_data))


0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object