In [3]:
import numpy as np

In [13]:
matrix = np.array([[3, 4, 9] ,[1, 2, 5], [4, 5, 6]])
matrix

array([[3, 4, 9],
       [1, 2, 5],
       [4, 5, 6]])

In [19]:
sub_matrix = matrix[0:1, 2:3]
print(sub_matrix)

[[9]]


In [33]:
sub_matrix = matrix[1:3, 1:4]
print(sub_matrix)

[[2 5]
 [5 6]]


In [39]:
element = matrix[1, 2]
print(element)

5


In [43]:
for row in matrix:
    for element in row:
        print(element, end= ', ')
    print("")


3, 4, 9, 
1, 2, 5, 
4, 5, 6, 


In [49]:
reshaped = matrix.reshape(9, 1)
print(reshaped)

[[3]
 [4]
 [9]
 [1]
 [2]
 [5]
 [4]
 [5]
 [6]]


In [55]:
matrix2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix2)

vstacked = np.vstack((matrix, matrix2))
print(vstacked)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 4 9]
 [1 2 5]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [57]:
hstacked = np.hstack((matrix, matrix2))
print(hstacked)

[[3 4 9 1 2 3]
 [1 2 5 4 5 6]
 [4 5 6 7 8 9]]


In [60]:
add_matrix = matrix2 + 10
print(add_matrix)

# Likewise for other math operations

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [62]:
broadcast_mult = matrix2 * np.array([1, 0, 1])
print(broadcast_mult)

# Likewise for other math operations

[[1 0 3]
 [4 0 6]
 [7 0 9]]


In [63]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

added_matrix = matrix1 + matrix2
print(added_matrix)

# Likewise for other math operations

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [69]:
matrix_dot_mult = np.dot(matrix1, matrix2)
print("Dot product: \n", matrix_dot_mult)

Dot product: 
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [70]:
transposed = matrix1.T
print(transposed)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
